# a mybinder.org-ready environment for demoing nodpy
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate nodpy-demo
#
name: nodpy-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.14,<3.15
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=22,<23
  - pip
  - wheel
  - debugpy
  - orjson
  - libcst
  - dacite
  - typer
  - nbformat
  - dataclasses-json
  - varname
  # additional packages for demos
  # - ipywidgets
